language: node_js
node_js:
  - "node"
env:
  - EXPORT_COVERAGE=1 CXX=g++-4.8
before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure -f noninteractive tzdata
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
