language: node_js
node_js:
  - "node"
env:
  - EXPORT_COVERAGE=1 CXX=g++-4.8
before_script:
  - export TZ='America/Sao_Paulo'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
